"""Initial Phase 1 schema, immutable migration."""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('lease_until', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('provider_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_code', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('context_length', sa.Integer(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('quality_status', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_models')),
    sa.UniqueConstraint('provider_code', 'model_id', name=op.f('uq_provider_models_provider_code')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_table('quota_buckets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=False),
    sa.Column('quota_date', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('reserved_usd', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('spent_usd', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('limit_usd', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quota_buckets')),
    sa.UniqueConstraint('scope', 'scope_id', 'quota_date', name=op.f('uq_quota_buckets_scope')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_table('runtime_locks',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_runtime_locks')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_table('sync_state',
    sa.Column('provider_code', sa.String(length=32), nullable=False),
    sa.Column('active_batch_id', sa.String(length=36), nullable=True),
    sa.Column('last_success_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('provider_code', name=op.f('pk_sync_state')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"), nullable=False),
    sa.Column('deleted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"), nullable=True),
    sa.Column('paid_blocked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('google_sub', name=op.f('uq_users_google_sub')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('explanation_mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"), nullable=False),
    sa.Column('deleted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_conversation_user_updated', 'conversations', ['user_id', 'updated_at', 'id'], unique=False)
    op.create_table('price_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('model_key', sa.String(length=36), nullable=False),
    sa.Column('input_per_m', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('output_per_m', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('request_price', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('fetched_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['model_key'], ['provider_models.id'], name=op.f('fk_price_snapshots_model_key_provider_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_snapshots')),
    sa.UniqueConstraint('batch_id', 'model_key', name=op.f('uq_price_snapshots_batch_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_price_snapshots_batch_id'), 'price_snapshots', ['batch_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"), nullable=False),
    sa.Column('revoked_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('extraction_status', sa.String(length=24), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"), nullable=False),
    sa.Column('expires_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_attachments_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attachments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_attachments_conversation_id'), 'attachments', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_attachments_user_id'), 'attachments', ['user_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('selected_model', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('context_truncated', sa.Boolean(), nullable=False),
    sa.Column('quota_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"), nullable=False),
    sa.Column('finished_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_runs_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_runs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs')),
    sa.UniqueConstraint('user_id', 'idempotency_key', name=op.f('uq_runs_user_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_runs_conversation_id'), 'runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_index(op.f('ix_runs_user_id'), 'runs', ['user_id'], unique=False)
    op.create_table('generation_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.String(length=32), nullable=False),
    sa.Column('generation_id', sa.String(length=255), nullable=True),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('actual_model', sa.String(length=255), nullable=True),
    sa.Column('actual_provider', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reserved_usd', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('actual_usd', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"), nullable=False),
    sa.Column('finished_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_generation_attempts_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_attempts')),
    sa.UniqueConstraint('provider_code', 'generation_id', name=op.f('uq_generation_attempts_provider_code')),
    sa.UniqueConstraint('run_id', 'attempt_no', name=op.f('uq_generation_attempts_run_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_generation_attempts_run_id'), 'generation_attempts', ['run_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_messages_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_run_id'), 'messages', ['run_id'], unique=False)
    op.create_table('tool_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=32), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_tool_runs_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_runs')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_tool_runs_run_id'), 'tool_runs', ['run_id'], unique=False)
    op.create_table('usage_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('provider_code', sa.String(length=32), nullable=False),
    sa.Column('generation_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('settled_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['generation_attempts.id'], name=op.f('fk_usage_ledger_attempt_id_generation_attempts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_ledger')),
    sa.UniqueConstraint('attempt_id', name=op.f('uq_usage_ledger_attempt_id')),
    sa.UniqueConstraint('provider_code', 'generation_id', name=op.f('uq_usage_ledger_provider_code')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
    op.bulk_insert(sa.table("runtime_locks", sa.column("name", sa.String)), [{"name": "admission"}])
    op.bulk_insert(sa.table("sync_state", sa.column("provider_code", sa.String)), [{"provider_code": "openrouter"}])

def downgrade():
    raise RuntimeError("Destructive schema downgrade is not supported")
