"""Invoked in a bounded subprocess by the worker. Input paths are generated by the server."""
import json
import resource
import subprocess
import sys
from pathlib import Path

from charset_normalizer import from_bytes
from PIL import Image
from pypdf import PdfReader

MAX_TEXT = 20000


def extract(path: Path, mime: str):
    if mime == "text/plain":
        data = path.read_bytes()
        if b"\0" in data:
            raise ValueError("FILE_ENCODING_INVALID")
        decoded = from_bytes(data).best()
        if decoded is None or decoded.chaos > 0.2:
            raise ValueError("FILE_ENCODING_INVALID")
        text = str(decoded)
    elif mime == "application/pdf":
        reader = PdfReader(path, strict=False)
        if reader.is_encrypted:
            raise ValueError("PDF_ENCRYPTED")
        if len(reader.pages) > 20:
            raise ValueError("PDF_PAGE_LIMIT")
        text = "\n".join(page.extract_text() or "" for page in reader.pages)
    elif mime in ("image/png", "image/jpeg"):
        Image.MAX_IMAGE_PIXELS = 20_000_000
        with Image.open(path) as image:
            if image.width * image.height > 20_000_000:
                raise ValueError("IMAGE_PIXEL_LIMIT")
            image.verify()
        process = subprocess.run(["tesseract", str(path), "stdout", "-l", "kor+eng"],
                                 capture_output=True, timeout=20)
        if process.returncode:
            raise ValueError("OCR_FAILED")
        text = process.stdout.decode("utf-8")
    else:
        raise ValueError("FILE_UNSUPPORTED")
    if not text.strip():
        raise ValueError("NO_EXTRACTABLE_TEXT")
    return {"text": text[:MAX_TEXT], "truncated": len(text) > MAX_TEXT}


def main():
    resource.setrlimit(resource.RLIMIT_CPU, (25, 25))
    if sys.platform == "linux":
        resource.setrlimit(resource.RLIMIT_AS, (512 * 1024**2, 512 * 1024**2))
    resource.setrlimit(resource.RLIMIT_FSIZE, (12 * 1024**2, 12 * 1024**2))
    try:
        result = extract(Path(sys.argv[1]), sys.argv[2])
    except subprocess.TimeoutExpired:
        result = {"error": "OCR_TIMEOUT"}
    except ValueError as exc:
        code = str(exc)
        allowed = {"FILE_ENCODING_INVALID", "PDF_ENCRYPTED", "PDF_PAGE_LIMIT", "IMAGE_PIXEL_LIMIT",
                   "OCR_FAILED", "FILE_UNSUPPORTED", "NO_EXTRACTABLE_TEXT"}
        result = {"error": code if code in allowed else "EXTRACTION_FAILED"}
    except Exception:
        result = {"error": "EXTRACTION_FAILED"}
    print(json.dumps(result, ensure_ascii=False))


if __name__ == "__main__":
    main()
