"""Invoked in a bounded subprocess by the worker. Input paths are generated by the server."""
import csv
import json
import os
import resource
import subprocess
import sys
import tempfile
import time
from pathlib import Path

from charset_normalizer import from_bytes
from PIL import Image
from pypdf import PdfReader

from .hangul import ERRORS as HANGUL_ERRORS
from .hangul import HWP_MIME, HWPX_MIME, hangul_text

MAX_TEXT = 20000


def image_text(path: Path) -> str:
    # Compare automatic layout with a text block. Keep automatic column ordering
    # unless the block pass recovers substantially more confident characters.
    # https://tesseract-ocr.github.io/tessdoc/ImproveQuality.html
    deadline = time.monotonic() + 20
    candidates = []
    with tempfile.TemporaryDirectory(prefix="modurouter-ocr-") as directory:
        for mode in (3, 6):
            output = Path(directory) / str(mode)
            process = subprocess.run(
                ["tesseract", str(path), str(output), "-l", "kor+eng", "--psm", str(mode), "txt", "tsv"],
                capture_output=True, timeout=max(0.01, deadline - time.monotonic()),
                env={**os.environ, "OMP_THREAD_LIMIT": "1"})
            if process.returncode:
                raise ValueError("OCR_FAILED")
            text = output.with_suffix(".txt").read_text(encoding="utf-8").strip()
            with output.with_suffix(".tsv").open(encoding="utf-8") as handle:
                words = [row for row in csv.DictReader(handle, delimiter="\t", quoting=csv.QUOTE_NONE)
                         if row["level"] == "5" and row.get("text", "").strip()]
            count = sum(len(word["text"]) for word in words)
            confident = sum(len(word["text"]) for word in words if float(word["conf"]) >= 60)
            score = sum(len(word["text"]) * max(0, float(word["conf"])) / 100 for word in words)
            candidates.append((text, count, confident, score))
    automatic, block = candidates
    selected = block if block[3] > automatic[3] * 1.2 else automatic
    text, count, confident, score = selected
    if not text:
        raise ValueError("NO_EXTRACTABLE_TEXT")
    if not count or confident / count < 0.6 or score / count < 0.55:
        raise ValueError("OCR_LOW_CONFIDENCE")
    return text


def extract(path: Path, mime: str):
    if mime == "text/plain":
        data = path.read_bytes()
        if b"\0" in data:
            raise ValueError("FILE_ENCODING_INVALID")
        decoded = from_bytes(data).best()
        if decoded is None or decoded.chaos > 0.2:
            raise ValueError("FILE_ENCODING_INVALID")
        text = str(decoded)
    elif mime in (HWP_MIME, HWPX_MIME):
        text = hangul_text(path, mime)
    elif mime == "application/pdf":
        reader = PdfReader(path, strict=False)
        if reader.is_encrypted:
            raise ValueError("PDF_ENCRYPTED")
        if len(reader.pages) > 20:
            raise ValueError("PDF_PAGE_LIMIT")
        text = "\n".join(page.extract_text() or "" for page in reader.pages)
    elif mime in ("image/png", "image/jpeg"):
        Image.MAX_IMAGE_PIXELS = 20_000_000
        with Image.open(path) as image:
            if image.width * image.height > 20_000_000:
                raise ValueError("IMAGE_PIXEL_LIMIT")
            image.verify()
        text = image_text(path)
    else:
        raise ValueError("FILE_UNSUPPORTED")
    if not text.strip():
        raise ValueError("NO_EXTRACTABLE_TEXT")
    return {"text": text[:MAX_TEXT], "truncated": len(text) > MAX_TEXT}


def main():
    resource.setrlimit(resource.RLIMIT_CPU, (25, 25))
    if sys.platform == "linux":
        resource.setrlimit(resource.RLIMIT_AS, (512 * 1024**2, 512 * 1024**2))
    resource.setrlimit(resource.RLIMIT_FSIZE, (12 * 1024**2, 12 * 1024**2))
    try:
        result = extract(Path(sys.argv[1]), sys.argv[2])
    except subprocess.TimeoutExpired:
        result = {"error": "OCR_TIMEOUT"}
    except ValueError as exc:
        code = str(exc)
        allowed = {"FILE_ENCODING_INVALID", "PDF_ENCRYPTED", "PDF_PAGE_LIMIT", "IMAGE_PIXEL_LIMIT",
                   "OCR_FAILED", "OCR_LOW_CONFIDENCE", "FILE_UNSUPPORTED", "NO_EXTRACTABLE_TEXT"} | HANGUL_ERRORS
        result = {"error": code if code in allowed else "EXTRACTION_FAILED"}
    except Exception:
        result = {"error": "EXTRACTION_FAILED"}
    print(json.dumps(result, ensure_ascii=False))


if __name__ == "__main__":
    main()
